### ISSUE TITLE
[EPIC] React Native dApp V2 - Milestone 1

### ISSUE THREAD

**Issue by crypblizz8** [WalletConnect/react-native-examples#10]
Overview
- Part One: Rework `react-native-dapp` to work with V2 #12 as MVP
- Part Two: Enhance MVP functionalities 
- Part Three: Enhance MVP functionalities
- Part Four: Create an SDK to make the implementation more dev friendly. 

Part One (v1.0)
- [x] - `Universal Provider` to wrap the component
- [x] - Connect + provide a `WCURI`
- [x] - Get Top 8 Explorer Listings + respective deeplinks
- [x] - Make a modal component
- [x] - Navigate with `app://wcuri....` on a V2 wallet
- [x] - Connection Made + User Address 🤝

Part Two (v1.1)
- [x] - https://github.com/WalletConnect/react-native-examples/pull/19
- [x] - https://github.com/WalletConnect/react-native-examples/pull/20
- [x] - https://github.com/WalletConnect/react-native-examples/pull/21
- [x] - https://github.com/WalletConnect/react-native-examples/pull/23

Part Three (v1.2)
- [x] - Move modal logic to a new package and use it in the example app
- [x] - Update docs

Part Four (v1.3)
- [x]  - Send PROJECT_ID as param
- [x] - Add ‘eth_sign’, ‘eth_transaction’ etc
- [x] - Add Smart contract methods via EIP1271 

Note: Have found `ethers` works in `v5` not current `v6` for React Native with their shim [package](https://github.com/WalletConnect/react-native-examples/issues/10) so this is something we need to keep in mind for future as UProvider requires the approach to work with `ethers.js`

**Comment by doutv** [comment]
@crypblizz8  Hello! Any update yet? We are developing a dapp based on WalletConnect V2 and eager to read your Docs. Thanks a lot!

**Comment by crypblizz8** [comment]
Hey @doutv, it is available here: https://github.com/WalletConnect/react-native-examples/tree/main/dapps/v2Explorer

Let me know what you think / any questions
