### ISSUE TITLE
[EPIC] Full Implementation + Designs for RN Wallets

### ISSUE THREAD

**Issue by crypblizz8** [WalletConnect/react-native-examples#8]
Overview
- We started this repo to add more examples / documentation for the React Native developers using WalletConnect SDKs
- This is the EPIC to get us to production for all Examples. 

Submodules builds. 
- `rn_cli_wallet_070_6`
- `rn_cli_wallet_069_7`
- `rn_cli_wallet_068_5`
- `rn_expo`

Stages
- [x] Add` rn_cli_wallet_068_5`
- [ ] Add `rn_cli_wallet_069_7`
- [x] Finish Barebones Instantiation (call methods etc) with Web3Wallet SDK (Sign + Auth)
- [x] Translate designs to it
- [ ] Expo Publish / TestFlight / Google Play Store Draft

**Comment by crypblizz8** [comment]
Current Progress / ToDo:
- [ ] eth_sendTransaction
- [ ] eth_signTransaction
- [ ] personal_sign
- [ ] eth_sign (standard)
- [ ] eth_signTypedData
- [ ] Ping for wallets
- [ ] Navigate to Session View. 
- [ ] object key mapping for other chains
- [ ] clean up all files with better commenting / notices 
- [ ] rm unused/ duplicate styles. 

QoL / Later
- [ ] Quick Loom Video
- [ ] QR Code
- [ ] Image Scroll transitions
